baseURL = "$HUGO_BASEURL"
title = "Art website"
# disableKinds = ["page", "section", "taxonomy", "term"]
timeout = 60000

# MENU --------------------------------
# -------------------------------------
[[menu.main]]
identifier = "gallery"
name = "Gallery"
url = "/gallery/"
weight = 1
[[menu.main]]
identifier = "bio"
name = "Bio"
url = "/biography/"
weight = 2
[[menu.main]]
identifier = "exhibitions"
name = "Exhibitions"
url = "/exhibitions/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10
pre = "hiddenMobile"
post = "icons/envelope-heart.svg"

# PARAMS ------------------------------
# -------------------------------------
[params]
favicon = ""
site_logo = ""
theme = "xtheme-pink"
# [outputs]
# #gallery = ["html", "json"]
# page = ["html", "json"]
# list = ["html", "json"]
# single = ["html", "json"]

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
