baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
# theme = ["github.com/cromozooom/calina"]

#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
# resourceDir = "../resources"


[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[[module.imports]]
path = "github.com/cromozooom/calina"
# [[module.mounts]]
# source = "static"
# target = "static"
# [[module.mounts]]
# source = "assets"
# target = "assets"
[[module.mounts]]
source = "layouts"
target = "examplesite/layouts"
[[module.mounts]]
source = "assets"
target = "examplesite/assets"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"
